name:        lox
version:     1.0
license:     CC0-1.0
author:      TheBizzle
maintainer:  TheBizzle
homepage:    https://github.com/TheBizzle
category:    Web
synopsis:    An implementation of the jlox programming language
description: An implementation of the jlox programming language, from Robert Nystrom's book Crafting Interpreters
stability:   Stable

language: GHC2024

default-extensions:
  - OverloadedRecordDot
  - OverloadedStrings

dependencies:
  - bizzlelude >= 4.20.2.0.3 && < 4.21
  - deepseq    >= 1.5.0      && < 1.6

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-import-lists
  - -Wredundant-constraints
  - -fno-warn-name-shadowing
  - -funbox-strict-fields
  - -O2

library:
  source-dirs: src/main
  dependencies:
    - containers >= 0.7   && < 0.8
    - mtl        >= 2.3.1 && < 2.4
    - text       >= 2.1.3 && < 2.2

executables:
  lox:
    source-dirs: app
    main:        Main.hs
    dependencies:
      - containers
      - lox
      - mtl
      - text
      - time >= 1.12.0 && < 1.13
